// conjunctions
export const API_PPDB = '/ppdb/conjunctions'
export const API_LPDB = '/launch-conjunctions'
export const API_OAUTH = '/oauth'
export const API_FAVORITE = '/interested-satellites'
export const API_FAVORITE_FIND = '/interested-satellites/find'
export const API_FAVORITE_CONJUNCTIONS = '/interested-satellites/conjunctions'
export const API_OAUTH_LOGOUT = '/oauth/logout'
export const API_TLES = '/tles'
export const API_RSOS = '/rso-params'
export const API_WCDB = '/watcher-catchers'
export const API_COLADB = '/collision-avoidance'
