export type modalType = 'LOGIN' | 'CONJUNCTIONS' | 'LAUNCHCONJUNCTIONS' | null

export const modalTypeData = {
  LOGIN: 'LOGIN',
  CONJUCTIONS: 'CONJUNCTIONS',
  LAUNCHCONJUNCTIONS: 'LAUNCHCONJUNCTIONS',
}
