export type modalType = 'LOGIN' | 'CONJUNCTIONS' | 'LAUNCHCONJUNCTIONS' | 'WATCHERCATCHER' | null

export const modalTypeData = {
  LOGIN: 'LOGIN',
  CONJUNCTIONS: 'CONJUNCTIONS',
  LAUNCHCONJUNCTIONS: 'LAUNCHCONJUNCTIONS',
  WATCHERCATCHER: 'WATCHERCATCHER',
}
